server:
  port: 8086

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserailization
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.package: "*"

  mail:
    host: smtp.gmail.com
    port: 587
    username: ansh2003mishra@gmail.com
    password: make_your_own_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    url: jdbc:postgresql://localhost:5432/marketplace
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

twilio:
  account-sid: don't_look_for_my_sid
  auth-token: make_your_own_auth-token
  from-number: and_yeah_number_too